services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_VARIABLE: ${VITE_VARIABLE}
    ports:
      - 80
    container_name: frontend-env-variables
    networks:
      - proxy

networks:
  proxy:
    external: true
    