version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_VARIABLE: ${VITE_VARIABLE}
    expose:
      - 80
    container_name: frontend-env-variables
